name: DevSecOps Pipeline Workflow

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

jobs:
  Static-Application-Security-Testing-SAST:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Perform ShiftLeft Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "java,javascript,credscan,depscan,python,html,go,jsp,node.js,bash"
        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SCAN_AUTO_BUILD: true

      - name: Upload ShiftLeft SAST reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shiftleft-sast-reports
          path: shiftleft

      - name: Run Semgrep scan
        run: |
          semgrep --json --output report.json --metrics=off --config="p/default" --verbose

      - name: Save Semgrep report as pipeline artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Semgrep-Report
          path: report.json

  Static-Code-Quality-Check:
    runs-on: self-hosted
    needs: Static-Application-Security-Testing-SAST
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 10
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  Secret-Scanning:
    runs-on: self-hosted
    needs: Static-Code-Quality-Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Secret Scanner
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.
        continue-on-error: true
  
      - name: Upload Secret Scanning reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: secret-scanning-reports
          path: secret-scanning-reports

  Build-Tag-Push-Scan:
    runs-on: self-hosted
    needs: Secret-Scanning
    steps:
      - name: Remove target directory with sudo
        run: sudo rm -rf /home/anshumaansingh10jan/actions-runner/_work/Boardgame-Pipeline/Boardgame-Pipeline/target

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
  
      - name: Build with Maven
        run: mvn package --file pom.xml
  
      - name: Upload build artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Boardgame
          path: target/*.jar
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build Docker Image
        run: docker build -t anshumaan10/boardgame:latest .
  
      - name: Trivy Image Scan
        run: trivy image --format table -o trivy-image-report.html anshumaan10/boardgame:latest
      
      - name: Upload Trivy Image Scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.html

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      # Push Docker image
      - name: Push Docker Image
        run: |
          docker push anshumaan10/boardgame:latest 

  Software-Composition-Analysis-SCA:
    runs-on: self-hosted
    needs: Build-Tag-Push-Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build project with Maven
        run: mvn clean install

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
        continue-on-error: true

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports

      - name: Trivy FS Scan
        run: trivy fs --format table -o trivy-fs-report.html .
    
      - name: Upload Trivy FS Scan report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report 
          path: trivy-fs-report.html


  kubernetes-deploy:
    runs-on: ubuntu-latest
    needs: Software-Composition-Analysis-SCA
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # #Uncomment and configure the following steps for Kubernetes deployment
      # - name: Set up Kubectl
      #   uses: tale/kubectl-action@v1
      #   with:
      #     base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f deployment-service.yaml -n webapps
      #     kubectl get svc -n webapps
