name: CICD Pipeline

on:
  push:
    branches: [ "main" ] # Trigger pipeline on push to main branch

jobs:
  build:
    runs-on: self-hosted # Use a self-hosted runner

    steps:
    - uses: actions/checkout@v3 # Check out the repository code

    - name: Set up JDK 17 # Set up Java Development Kit 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven # Build the project using Maven
      run: mvn package --file pom.xml

    - uses: actions/upload-artifact@v4 # Upload the built JAR artifact
      with:
        name: Boardgame
        path: target/*.jar

    - name: Trivy FS Scan # Perform file system scan with Trivy
      run: |
        trivy fs --format table -o trivy-fs-report.html .

    - name: SonarQube Scan # Run SonarQube scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Install jq # Install jq for JSON processing
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: SonarQube Quality Gate check # Check SonarQube Quality Gate status
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5 # Fail the step after 5 minutes if not completed
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Set up QEMU # Set up QEMU for cross-platform builds
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx # Set up Docker Buildx for multi-platform builds
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image # Build the Docker image
      run: |
        docker build -t anshumaan10/boardgame:latest .

    - name: Trivy Image Scan # Perform image scan with Trivy
      run: |
        trivy image --format table -o trivy-image-report.html anshumaan10/board:latest

    - name: Login to Docker Hub # Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image # Push the Docker image to Docker Hub
      run: |
        docker push anshumaan10/board:latest

    - name: Kubectl Action # Apply Kubernetes deployment and service
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}

    - run: |
        kubectl apply -f deployment-service.yaml -n webapps # Apply Kubernetes manifests
        kubectl get svc -n webapps # List services in the 'webapps' namespace
