name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

  setup-java:
    runs-on: self-hosted
    needs: checkout
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

  build:
    runs-on: self-hosted
    needs: setup-java
    steps:
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Boardgame
        path: target/*.jar

  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  trivy-fs-scan:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Trivy FS Scan
      run: |
        trivy fs --format table -o trivy-fs-report.html .
    
    - name: Upload Trivy FS Scan report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-fs-report
        path: trivy-fs-report.html

  sonarqube-scan:
    runs-on: self-hosted
    needs: build
    steps:
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  install-jq:
    runs-on: self-hosted
    needs: sonarqube-scan
    steps:
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

  sonarqube-quality-gate-check:
    runs-on: self-hosted
    needs: install-jq
    steps:
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  setup-qemu:
    runs-on: self-hosted
    needs: sonarqube-quality-gate-check
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

  setup-buildx:
    runs-on: self-hosted
    needs: setup-qemu
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

  build-docker-image:
    runs-on: self-hosted
    needs: setup-buildx
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: Boardgame

    - name: Build Docker Image
      run: docker build -t anshumaan10/boardgame:latest .

  trivy-image-scan:
    runs-on: self-hosted
    needs: build-docker-image
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write
    steps:
    - name: Trivy Image Scan
      run: |
        trivy image --format table -o trivy-image-report.html anshumaan10/boardgame:latest
    
    - name: Upload Trivy Image Scan report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-image-report
        path: trivy-image-report.html

  docker-login:
    runs-on: self-hosted
    needs: trivy-image-scan
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  push-docker-image:
    runs-on: self-hosted
    needs: docker-login
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write
    steps:
    - name: Push Docker Image
      uses: docker/build-push-action@v6
      with:
        tags: anshumaan10/boardgame:latest

  kubectl-apply:
    runs-on: self-hosted
    needs: push-docker-image
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write
    steps:
    - name: Kubectl Action
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    - run: |
        kubectl apply -f deployment-service.yaml -n webapps
        kubectl get svc -n webapps
