name: ZAP Full Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.10.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'https://demo.testfire.net'
        fail_action: 'false'
        rules_file_name: '.zap/rules.tsv'

    - name: Upload JSON report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-json
        path: report_json.json

    - name: Upload Markdown report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-md
        path: report_md.md

    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-html
        path: report_html.html
