name: ZAP Full Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
          # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.6.1
      with:
        docker_name: 'owasp/zap2docker-stable'
        target: 'http://testphp.vulnweb.com/'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
      
        
    - name: Upload JSON report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-json
        path: report_json.json

    - name: Upload Markdown report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-md
        path: report_md.md

    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report-html
        path: report_html.html
