name: Insider Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  insider-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Insider tool
        run: wget https://github.com/insidersec/insider/releases/download/2.1.0/insider_2.1.0_linux_x86_64.tar.gz

      - name: Extract Insider tool
        run: tar -xf insider_2.1.0_linux_x86_64.tar.gz

      - name: Make Insider executable
        run: chmod +x insider

      - name: Run Insider Security Scan on src directory
        run: |
          ./insider -tech java -target ./src -exclude node_modules/* -exclude tests/* -v 

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: insider-html-report
          path: ./insider-report.html

      - name: Upload JSON Report
        uses: actions/upload-artifact@v3
        with:
          name: insider-json-report
          path: ./insider-report.json
