name: Kubernetes-Deploy-and-Audit

on:
  workflow_dispatch

jobs:
  kubernetes-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  
      packages: write
      security-events: write
      statuses: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Set up Google Cloud SDK
        run: |
          curl -sO https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-390.0.0-linux-x86_64.tar.gz
          tar -zxvf google-cloud-sdk-390.0.0-linux-x86_64.tar.gz
          ./google-cloud-sdk/install.sh -q
          source ./google-cloud-sdk/path.bash.inc

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin


      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: Deploy to Kubernetes
        run: |
          retries=5
          until kubectl apply -f deployment-service.yaml -n webapps --validate=false || [ $retries -le 0 ]; do
            echo "Retrying... $((retries--)) left"
            sleep 5
          done

      - name: Get Services
        run: |
          kubectl get svc -n webapps

    
