name: Kubernetes-Deploy-and-Audit

on:
  workflow_dispatch

jobs:
  kubernetes-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  
      packages: write
      security-events: write
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg
          echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up kubectl
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Deploy to Kubernetes
        run: |
          retries=5
          until kubectl apply -f deployment-service.yaml -n webapps --validate=false || [ $retries -le 0 ]; do
            echo "Retrying... $((retries--)) left"
            sleep 5
          done

      - name: Get Services
        run: |
          kubectl get svc -n webapps
