name: Java CI with Maven & Mend Image Scan

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t anshumaan10/boardgame:latest .

    - name: Trivy Image Scan
      run: |
        trivy image --format table -o trivy-image-report.html anshumaan10/boardgame:latest
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        docker push anshumaan10/boardgame:latest

  
    - name: Run Mend Image Scan
      env:
        MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
        MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
        MEND_URL: https://saas.whitesourcesoftware.com
      run: |
        echo "Running Mend Image Scan"
        mend image anshumaan10/boardgame:latest --format json --filename mend-image-scan.json --local-pull

    - name: Convert Mend JSON to SARIF
      run: python convert_mend_json_to_sarif.py mend-image-scan.json mend-image-scan.sarif

    - name: Upload Mend SARIF results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: mend-image-scan.sarif

