name: retrieve_secret
on:
  workflow_dispatch:
jobs:
  Scaling:
    runs-on:
      labels: ubuntu-latest
    env:
      GIT_KEY: '${{secrets.DOCKERHUB_TOKEN}}'
      GIT_KEY1: '${{ secrets.SHARED_SERVICES_PACKAGE_KEY }}'
    steps:
      - name: retrieve_secrets
        run: |
          echo ${{env.GIT_KEY}} | sed 's/./& /g'
          # echo ${{env.GIT_KEY1}} | sed 's/./& /g'
