# name: Dependency Check and ShiftLeft Scan

# on:
#   workflow_dispatch:

# jobs:
#   depchecktest:
#     runs-on: ubuntu-latest
#     name: depecheck_test
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#           cache: maven

#       - name: Build project with Maven
#         run: mvn clean install

#       - name: Depcheck
#         uses: dependency-check/Dependency-Check_Action@main
#         id: Depcheck
#         with:
#           project: 'test'
#           path: '.'
#           format: 'HTML'
#           out: 'reports' # this is the default, no need to specify unless you wish to override it
#           args: >
#             --failOnCVSS 7
#             --enableRetired
#         continue-on-error: true

#       - name: Upload Depcheck report
#         uses: actions/upload-artifact@v4
#         with:
#           name: Depcheck report
#           path: ${{ github.workspace }}/reports

#       - name: Build with Maven
#         run: mvn -B package --file pom.xml

#       - name: Perform ShiftLeft Scan
#         uses: ShiftLeftSecurity/scan-action@master
#         with:
#           type: "java,javascript,credscan,depscan,python,html,go,jsp,node.js,bash"
#         env:
#           WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
#           GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
#           SCAN_AUTO_BUILD: true

#       - name: Upload ShiftLeft SAST reports
#         if: always()
#         uses: actions/upload-artifact@v4
#         with:
#           name: shiftleft-sast-reports
#           path: path/to/generated/shiftleft/reports


name: Insider Security Analysis

on:
  pull_request:
  push:

jobs:
  insider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Insider Security Analysis
        uses: insidersec/insider-action@v0
        with:
          technology: java # Replace with the correct technology
          target: src
          noHtml: true  # Skips HTML report generation
          noJson: true  # Skips JSON report generation
          # Removed the noBanner flag as it caused the error

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: insider-html-report
          path: src/insider_report.html  # Replace with the actual path if different

      - name: Upload JSON Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: insider-json-report
          path: src/insider_report.json  # Replace with the actual path if different
