name: Anchore SBOM Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      actions: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
            # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull anshumaan10/boardgame:latest

      - name: Run Anchore SBOM Scan
        run: |
          # Replace with your Anchore CLI command to perform SBOM scan
          anchore-cli image add anshumaan10/boardgame:latest
          anchore-cli image vuln anshumaan10/boardgame:latest all

      - name: Generate SBOM Report
        run: |
          # Replace with your command to generate SBOM report
          anchore-cli image sbom anshumaan10/boardgame:latest > sbom-report.json

      - name: Upload SBOM Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom-report
          path: sbom-report.json
