name: slack_github_action
on: [push]
jobs:
  slack_notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
            "text": "Git push done in the repo , Boardgame-Pipeline"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
