name: Slack Notification

on:
  workflow_dispatch:

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    name: Post to Slack
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
