name: Slack Notification

on:
  workflow_dispatch:

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    name: Post to Slack
    steps:
      - name: Checkout
        uses: actions/checkout@v2

    
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
        if: always() # Pick up events even if the job fails or is canceled.
