name: Slack Notification

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: docker.pkg.github.com
      IMAGE_NAME: ${{ github.repository }}/alerta-cli
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#devsecops'
          message: Starting Docker Build and Push...
        if: always()
