name: Slack Notification

on:
  workflow_dispatch:

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    name: Post to Slack
    steps:
      - name: Checkout
        uses: actions/checkout@v2

    
      - uses: act10ns/slack@v2.1.0
        with:
          status: ${{ job.status }}
          #fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
          message: "It started"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # Pick up events even if the job fails or is canceled.
