name: Slack Notification with Artifact

on: [push]

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          echo "Test results" > test-results.txt
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt

      - name: Get artifact download URL
        id: get-url
        run: |
          curl -s \
            -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
            | jq -r '.artifacts[0].id' > artifact_id
          curl -s \
            -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$(cat artifact_id)/zip \
            | jq -r '.url' > download_url
          echo "artifact_download_url=$(cat download_url)" >> $GITHUB_ENV
      - name: Send notification on Slack using Webhooks
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Repository:* anshumaan-10/Boardgame-Pipeline\n*Branch:* main\n*Commit ID:* b14a40f2c8e619ca44ddca29571468e1c7b41d54\n*Commit Message:* Update slack.yml\n*Author:* ANSHUMAAN SINGH\n*Build Status:* success\n*Commit URL:* https://github.com/anshumaan-10/Boardgame-Pipeline/commit/b14a40f2c8e619ca44ddca29571468e1c7b41d54\n*Artifact URL:* [Download Artifact](${{ env.artifact_download_url }})"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
