name: Slack Notification

on:
  workflow_dispatch:

jobs:
  slack-notification:
    runs-on: ubuntu-latest
    name: Post to Slack
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'devsecops'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: T07EWGHQEFN/B07FGTKQNSU/lJv6HfAPBQgrKoXH95atByCe
