name: Slack Notification with Artifact

on: [push]

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          echo "Test results" > test-results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt

      - name: Get artifact download URL
        id: get-url
        run: |
          artifact_id=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
            | jq -r '.artifacts[0].id')
          download_url="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip"
          echo "artifact_download_url=$download_url" >> $GITHUB_ENV

      - name: Construct curl command for Slack
        id: construct-curl
        run: |
          curl_command="curl -L -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.TOKEN_GITHUB }}' -H 'X-GitHub-Api-Version: 2022-11-28' ${artifact_download_url} --output artifact.zip"
          echo "curl_command=$curl_command" >> $GITHUB_ENV

      - name: Send notification on Slack using Webhooks
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Repository:* anshumaan-10/Boardgame-Pipeline\n*Branch:* main\n*Commit ID:* ${{ github.sha }}\n*Commit Message:* ${{ github.event.head_commit.message }}\n*Author:* ${{ github.event.head_commit.author.name }}\n*Build Status:* ${{ job.status }}\n*Commit URL:* ${{ github.event.head_commit.url }}\n*Artifact URL:* [Download Artifact](${artifact_download_url})\n\nUse the following command to download:\n```${{ env.curl_command }}```"
                      }
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
