name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Check-Maven-Wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Install Maven
        run: sudo apt-get install maven -y
      
      - name: Verify Maven Wrapper files
        run: |
          ls -la
          ls -la ./mvnw
          ls -la .mvn/wrapper/
          cat .mvn/wrapper/maven-wrapper.properties
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: "test"


        name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Check-Maven-Wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Verify Maven Wrapper files
        run: |
          ls -la .mvn/wrapper/
          cat .mvn/wrapper/maven-wrapper.properties
          ls -la

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: "test"


