name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  Check-Maven-Wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Give execute permission to mvnw
        run: chmod +x ./mvnw
      
      - name: Verify Maven Wrapper files
        run: |
          ls -la
          ls -la ./mvnw
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

